CREATE DATABASE IF NOT EXISTS wallet_db;
USE wallet_db;

CREATE TABLE wallets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  userId INT NOT NULL,
  balance DECIMAL(10,2) DEFAULT 0.00,
  createdAt BIGINT DEFAULT (UNIX_TIMESTAMP())
);